language: objective-c
osx_image: xcode7.3

# cache: 
  # directories:
    # - vendor/bundle
# install:
  # - brew update && (brew upgrade xctool || true) && (brew install xcproj || true) && xctool --version
  # - bundle install --path=vendor/bundle --binstubs=vendor/bin
  # - cd Example && bundle exec pod install && cd -


podfile: Example/Podfile
# cache: cocoapods
# podfile: Example/Podfile
#before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
install:
  - pod update
script:
 - xctool -workspace Example/EMEmojiableBtn.xcworkspace -scheme EMEmojiableBtn-Example -sdk iphoneos9.3 build test CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY=""